# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xolo/q1100/setup-makefiles.sh

# ADSPS 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/adsprpcd:system/bin/adsprpcd \
	vendor/xolo/q1100/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
	vendor/xolo/q1100/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:system/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
	vendor/xolo/q1100/proprietary/vendor/lib/rfsa/adsp/libapps_mem_heap.so:system/vendor/lib/rfsa/adsp/libapps_mem_heap.so \
	vendor/xolo/q1100/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:system/vendor/lib/rfsa/adsp/libdspCV_skel.so \
	vendor/xolo/q1100/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:system/vendor/lib/rfsa/adsp/libfastcvadsp.so \
	vendor/xolo/q1100/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:system/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
	vendor/xolo/q1100/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
	vendor/xolo/q1100/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
	vendor/xolo/q1100/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
	vendor/xolo/q1100/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
	vendor/xolo/q1100/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
	vendor/xolo/q1100/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
	vendor/xolo/q1100/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb \
	vendor/xolo/q1100/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
	vendor/xolo/q1100/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
	vendor/xolo/q1100/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
	vendor/xolo/q1100/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so
# Bluetooth 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/xolo/q1100/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/xolo/q1100/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so
# Camera 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/xolo/q1100/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
	vendor/xolo/q1100/proprietary/lib/hw/camera.msm8226.so:system/lib/hw/camera.msm8226.so \
	vendor/xolo/q1100/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
	vendor/xolo/q1100/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
	vendor/xolo/q1100/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
	vendor/xolo/q1100/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov12830.so:system/vendor/lib/libmmcamera_ov12830.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov5648.so:system/vendor/lib/libmmcamera_ov5648.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_gc2235_huaquan.so:system/vendor/lib/libmmcamera_gc2235_huaquan.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov9760_q1v05a.so:system/vendor/lib/libmmcamera_ov9760_q1v05a.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov9724.so:system/vendor/lib/libmmcamera_ov9724.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so:system/vendor/lib/libmmcamera_skuf_ov12830_p12v01c.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov2720.so:system/vendor/lib/libmmcamera_ov2720.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov12830_mcnex.so:system/vendor/lib/libmmcamera_ov12830_mcnex.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so:system/vendor/lib/libmmcamera_SKUAA_ST_gc0339.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so:system/vendor/lib/libmmcamera_SKUAB_ST_s5k4e1.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_sp1628.so:system/vendor/lib/libmmcamera_sp1628.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov5648_oty5f03.so:system/vendor/lib/libmmcamera_ov5648_oty5f03.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_hi256.so:system/vendor/lib/libmmcamera_hi256.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov9760_eeprom.so:system/vendor/lib/libmmcamera_ov9760_eeprom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_s5k3h7.so:system/vendor/lib/libmmcamera_s5k3h7.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov8865_qtech.so:system/vendor/lib/libmmcamera_ov8865_qtech.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_hi841_qtech.so:system/vendor/lib/libmmcamera_hi841_qtech.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:system/vendor/lib/libmmcamera_ov8865_q8v18a.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_s5k3l1yx.so:system/vendor/lib/libmmcamera_s5k3l1yx.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_mt9m114.so:system/vendor/lib/libmmcamera_mt9m114.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so:system/vendor/lib/libmmcamera_skuab_shinetech_gc0339.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_gc2235_imatec.so:system/vendor/lib/libmmcamera_gc2235_imatec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so:system/vendor/lib/libmmcamera_skuf_ov5648_p5v23c.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov5648_sunrise.so:system/vendor/lib/libmmcamera_ov5648_sunrise.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov8825.so:system/vendor/lib/libmmcamera_ov8825.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov5648_mcnex.so:system/vendor/lib/libmmcamera_ov5648_mcnex.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_ov12830_sunrise.so:system/vendor/lib/libmmcamera_ov12830_sunrise.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmcamera_imx134.so:system/vendor/lib/libmmcamera_imx134.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
	vendor/xolo/q1100/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw

# Chromatix 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_gc2235_imatec_default_video.so:system/vendor/lib/libchromatix_gc2235_imatec_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_gc2235_huaquan_common.so:system/vendor/lib/libchromatix_gc2235_huaquan_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9724_common.so:system/vendor/lib/libchromatix_ov9724_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so:system/vendor/lib/libchromatix_ov5648_oty5f03_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:system/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_liveshot.so:system/vendor/lib/libchromatix_s5k3l1yx_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_preview_hd.so:system/vendor/lib/libchromatix_ov8825_preview_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_snapshot.so:system/vendor/lib/libchromatix_ov8865_qtech_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_common.so:system/vendor/lib/libchromatix_ov5648_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_liveshot_hd.so:system/vendor/lib/libchromatix_ov8825_liveshot_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_snapshot.so:system/vendor/lib/libchromatix_ov5648_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_default_video.so:system/vendor/lib/libchromatix_ov8825_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_common.so:system/vendor/lib/libchromatix_ov8825_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_preview.so:system/vendor/lib/libchromatix_ov8825_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_common.so:system/vendor/lib/libchromatix_ov12830_mcnex_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_hi841_qtech_preview.so:system/vendor/lib/libchromatix_hi841_qtech_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9724_default_video.so:system/vendor/lib/libchromatix_ov9724_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_liveshot.so:system/vendor/lib/libchromatix_ov12830_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_video_hd.so:system/vendor/lib/libchromatix_ov12830_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_hfr_60fps.so:system/vendor/lib/libchromatix_ov12830_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_snapshot_hd.so:system/vendor/lib/libchromatix_ov8825_snapshot_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:system/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_zsl.so:system/vendor/lib/libchromatix_ov12830_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov2720_zsl.so:system/vendor/lib/libchromatix_ov2720_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_snapshot.so:system/vendor/lib/libchromatix_s5k3l1yx_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_mcnex_preview.so:system/vendor/lib/libchromatix_ov5648_mcnex_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_zsl.so:system/vendor/lib/libchromatix_ov12830_sunrise_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_default_video.so:system/vendor/lib/libchromatix_ov12830_sunrise_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_common.so:system/vendor/lib/libchromatix_ov12830_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_snapshot.so:system/vendor/lib/libchromatix_ov12830_mcnex_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_liveshot.so:system/vendor/lib/libchromatix_ov12830_mcnex_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov2720_default_video.so:system/vendor/lib/libchromatix_ov2720_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_video_hd.so:system/vendor/lib/libchromatix_s5k3l1yx_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_video_hd.so:system/vendor/lib/libchromatix_ov8825_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_sunrise_default_video.so:system/vendor/lib/libchromatix_ov5648_sunrise_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_sunrise_preview.so:system/vendor/lib/libchromatix_ov5648_sunrise_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx134_hfr_120.so:system/vendor/lib/libchromatix_imx134_hfr_120.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_preview.so:system/vendor/lib/libchromatix_s5k3l1yx_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_default_video.so:system/vendor/lib/libchromatix_ov5648_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_default_video.so:system/vendor/lib/libchromatix_ov12830_mcnex_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3h7_snapshot.so:system/vendor/lib/libchromatix_s5k3h7_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_hfr_60fps.so:system/vendor/lib/libchromatix_ov8825_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov2720_preview.so:system/vendor/lib/libchromatix_ov2720_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_mcnex_common.so:system/vendor/lib/libchromatix_ov5648_mcnex_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3h7_preview.so:system/vendor/lib/libchromatix_s5k3h7_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_hi841_qtech_snapshot.so:system/vendor/lib/libchromatix_hi841_qtech_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_qtech_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_video_hd.so:system/vendor/lib/libchromatix_ov8865_qtech_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx134_preview.so:system/vendor/lib/libchromatix_imx134_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_zsl.so:system/vendor/lib/libchromatix_ov12830_mcnex_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_gc2235_huaquan_default_video.so:system/vendor/lib/libchromatix_gc2235_huaquan_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_preview.so:system/vendor/lib/libchromatix_ov9760_q1v05a_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_sunrise_common.so:system/vendor/lib/libchromatix_ov5648_sunrise_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_preview.so:system/vendor/lib/libchromatix_ov12830_sunrise_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:system/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_common.so:system/vendor/lib/libchromatix_s5k3l1yx_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx134_hfr_60.so:system/vendor/lib/libchromatix_imx134_hfr_60.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_preview.so:system/vendor/lib/libchromatix_ov5648_oty5f03_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_snapshot.so:system/vendor/lib/libchromatix_ov8825_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_zsl.so:system/vendor/lib/libchromatix_ov8865_qtech_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_gc2235_huaquan_preview.so:system/vendor/lib/libchromatix_gc2235_huaquan_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_liveshot.so:system/vendor/lib/libchromatix_ov9760_q1v05a_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3h7_common.so:system/vendor/lib/libchromatix_s5k3h7_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_snapshot.so:system/vendor/lib/libchromatix_ov12830_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_qtech_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_common.so:system/vendor/lib/libchromatix_ov9760_q1v05a_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_preview.so:system/vendor/lib/libchromatix_ov12830_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so:system/vendor/lib/libchromatix_ov5648_oty5f03_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_common.so:system/vendor/lib/libchromatix_ov12830_sunrise_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_hfr_90fps.so:system/vendor/lib/libchromatix_ov12830_sunrise_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_liveshot.so:system/vendor/lib/libchromatix_ov12830_sunrise_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_mcnex_default_video.so:system/vendor/lib/libchromatix_ov5648_mcnex_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_hfr_60fps.so:system/vendor/lib/libchromatix_ov12830_mcnex_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_gc2235_imatec_preview.so:system/vendor/lib/libchromatix_gc2235_imatec_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_hfr_120fps.so:system/vendor/lib/libchromatix_ov12830_sunrise_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_preview.so:system/vendor/lib/libchromatix_ov8865_qtech_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_video_hd.so:system/vendor/lib/libchromatix_ov12830_mcnex_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_preview.so:system/vendor/lib/libchromatix_ov5648_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_hfr_90fps.so:system/vendor/lib/libchromatix_ov8825_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3h7_default_video.so:system/vendor/lib/libchromatix_s5k3h7_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx134_common.so:system/vendor/lib/libchromatix_imx134_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_default_video.so:system/vendor/lib/libchromatix_s5k3l1yx_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:system/vendor/lib/libchromatix_ov8865_q8v18a_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_gc2235_imatec_common.so:system/vendor/lib/libchromatix_gc2235_imatec_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_zsl.so:system/vendor/lib/libchromatix_s5k3l1yx_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9760_q1v05a_default_video.so:system/vendor/lib/libchromatix_ov9760_q1v05a_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx134_default_video.so:system/vendor/lib/libchromatix_imx134_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_common.so:system/vendor/lib/libchromatix_ov5648_oty5f03_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_hfr_120fps.so:system/vendor/lib/libchromatix_ov12830_mcnex_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_video_hd.so:system/vendor/lib/libchromatix_ov12830_sunrise_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov2720_common.so:system/vendor/lib/libchromatix_ov2720_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov2720_liveshot.so:system/vendor/lib/libchromatix_ov2720_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_default_video.so:system/vendor/lib/libchromatix_ov8865_qtech_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_hi841_qtech_default_video.so:system/vendor/lib/libchromatix_hi841_qtech_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so:system/vendor/lib/libchromatix_skuf_ov12830_p12v01c_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9724_liveshot.so:system/vendor/lib/libchromatix_ov9724_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov2720_hfr.so:system/vendor/lib/libchromatix_ov2720_hfr.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_liveshot.so:system/vendor/lib/libchromatix_ov8865_qtech_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_hi841_qtech_common.so:system/vendor/lib/libchromatix_hi841_qtech_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_sunrise_snapshot.so:system/vendor/lib/libchromatix_ov5648_sunrise_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_hfr_90fps.so:system/vendor/lib/libchromatix_ov12830_mcnex_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:system/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx134_snapshot.so:system/vendor/lib/libchromatix_imx134_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_liveshot.so:system/vendor/lib/libchromatix_ov8825_liveshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_120fps.so:system/vendor/lib/libchromatix_ov8865_qtech_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_snapshot.so:system/vendor/lib/libchromatix_ov12830_sunrise_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_mcnex_preview.so:system/vendor/lib/libchromatix_ov12830_mcnex_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_mcnex_snapshot.so:system/vendor/lib/libchromatix_ov5648_mcnex_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_hfr_90fps.so:system/vendor/lib/libchromatix_ov12830_hfr_90fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:system/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_qtech_common.so:system/vendor/lib/libchromatix_ov8865_qtech_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_default_video.so:system/vendor/lib/libchromatix_ov12830_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_video_hd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_zsl.so:system/vendor/lib/libchromatix_ov8825_zsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_sunrise_hfr_60fps.so:system/vendor/lib/libchromatix_ov12830_sunrise_hfr_60fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so:system/vendor/lib/libchromatix_skuf_ov5648_p5v23c_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so:system/vendor/lib/libchromatix_SKUAB_ST_s5k4e1_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so:system/vendor/lib/libchromatix_skuab_shinetech_gc0339_snapshot.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov9724_preview.so:system/vendor/lib/libchromatix_ov9724_preview.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov12830_hfr_120fps.so:system/vendor/lib/libchromatix_ov12830_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:system/vendor/lib/libchromatix_ov8865_q8v18a_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov8825_hfr_120fps.so:system/vendor/lib/libchromatix_ov8825_hfr_120fps.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so:system/vendor/lib/libchromatix_SKUAA_ST_gc0339_common.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so:system/vendor/lib/libchromatix_ov5648_oty5f03_default_video.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/vendor/lib/libchromatix_s5k3l1yx_hfr_60fps.so

# Color convertor 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so

# DRM 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/qseecomd:system/bin/qseecomd \
	vendor/xolo/q1100/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
	vendor/xolo/q1100/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
	vendor/xolo/q1100/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	#vendor/xolo/q1100/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdrmdiag.so:system/vendor/lib/libdrmdiag.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
	vendor/xolo/q1100/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so

# GPS
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
	vendor/xolo/q1100/proprietary/bin/location-mq:system/bin/location-mq \
	vendor/xolo/q1100/proprietary/bin/lowi-server:system/bin/lowi-server \
	vendor/xolo/q1100/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
	vendor/xolo/q1100/proprietary/bin/quipc_main:system/bin/quipc_main \
	vendor/xolo/q1100/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
	vendor/xolo/q1100/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent \
	vendor/xolo/q1100/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
	vendor/xolo/q1100/proprietary/etc/cacert_location.pem:system/etc/cacert_location.pem \
	vendor/xolo/q1100/proprietary/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem \
	vendor/xolo/q1100/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/xolo/q1100/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
	vendor/xolo/q1100/proprietary/lib/libnl_2.so:system/lib/libnl_2.so \
	#vendor/xolo/q1100/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libquipc_ulp_adapter.so:system/vendor/lib/libquipc_ulp_adapter.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
	#vendor/xolo/q1100/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
	#vendor/xolo/q1100/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libxtwifi_zpp_adaptor.so:system/vendor/lib/libxtwifi_zpp_adaptor.so

# Graphics
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
	vendor/xolo/q1100/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
	vendor/xolo/q1100/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
	vendor/xolo/q1100/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	vendor/xolo/q1100/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	vendor/xolo/q1100/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	vendor/xolo/q1100/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
	vendor/xolo/q1100/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
	vendor/xolo/q1100/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a2xx.so

# Keystore 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/vendor/firmware/keymaster/keymaster.b00:system/vendor/firmware/keymaster/keymaster.b00 \
	vendor/xolo/q1100/proprietary/vendor/firmware/keymaster/keymaster.b01:system/vendor/firmware/keymaster/keymaster.b01 \
	vendor/xolo/q1100/proprietary/vendor/firmware/keymaster/keymaster.b02:system/vendor/firmware/keymaster/keymaster.b02 \
	vendor/xolo/q1100/proprietary/vendor/firmware/keymaster/keymaster.b03:system/vendor/firmware/keymaster/keymaster.b03 \
	vendor/xolo/q1100/proprietary/vendor/firmware/keymaster/keymaster.mdt:system/vendor/firmware/keymaster/keymaster.mdt

# Media 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
	#vendor/xolo/q1100/proprietary/vendor/lib/libHevcSwDecoder.so:system/vendor/lib/libHevcSwDecoder.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblistenhardware.so:system/vendor/lib/liblistenhardware.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblistensoundmodel.so:system/vendor/lib/liblistensoundmodel.so \
	vendor/xolo/q1100/proprietary/vendor/lib/liblisten.so:system/vendor/lib/liblisten.so \
	vendor/xolo/q1100/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
	vendor/xolo/q1100/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
	vendor/xolo/q1100/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
	#vendor/xolo/q1100/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
	vendor/xolo/q1100/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
	vendor/xolo/q1100/proprietary/etc/permissions/ims.xml:system/etc/permissions/ims.xml

# Perf 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/xolo/q1100/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so

# Postprocessing 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
	vendor/xolo/q1100/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so

# Qualcomm 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/irsc_util:system/bin/irsc_util \
	vendor/xolo/q1100/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so

# Radio 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/xolo/q1100/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/xolo/q1100/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/xolo/q1100/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libdsnetutils.so:system/vendor/lib/libdsnetutils.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so

# Sensors
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
	vendor/xolo/q1100/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libAKM8963.so:system/vendor/lib/libAKM8963.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so

# Thermal
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/thermal-engine:system/bin/thermal-engine \
	vendor/xolo/q1100/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so

# Time services
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/time_daemon:system/bin/time_daemon \
	vendor/xolo/q1100/proprietary/vendor/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
	vendor/xolo/q1100/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so

# Venus firmware 
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
	vendor/xolo/q1100/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt

# Wifi
PRODUCT_COPY_FILES += \
	vendor/xolo/q1100/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
	vendor/xolo/q1100/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
	vendor/xolo/q1100/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini:system/etc/firmware/wlan/prima/WCNSS_qcom_cfg.ini \
	vendor/xolo/q1100/proprietary/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin:system/etc/firmware/wlan/prima/WCNSS_qcom_wlan_nv.bin \
	vendor/xolo/q1100/proprietary/lib/libqminvapi.so:system/lib/libqminvapi.so